### ISSUE TITLE
Path to backup is missing at startup

### ISSUE THREAD

**Issue by jspittka** [contextnerror/ICC-Mac#4]
After installation out of the box the app throws an error at startup:

"Error creating backup. Could not find a part of the path "C:\var\folders\q8\mj64r76d4c9b8xsqnhkhs1z00000gn\T\sometmpFile.tmp"."

This can be resolved by creating the path to the tmp file in the package contents. No file is ever created there, it just avoids the error. Backups are still generated in the normal location "drive_c/ProgramData/Ice Cream Calculator/Backup".

**Comment by contextnerror** [comment]
Thanks for the tip, it does seem to fix it. In my case the path had a different string of letters, so I'm not sure if I could preemptively apply this fix to the bundle. But I have now included a note about it so hopefully people can do it on their own.
